"""Initial CyberPass schema.

Revision ID: 438decdd6c95
Revises:
Create Date: 2026-08-04 21:15:51.760720
Author: Plessy Vincent
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "438decdd6c95"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("slug", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index(
        op.f("ix_organizations_deleted_at"), "organizations", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_org_created", "audit_events", ["organization_id", "created_at"], unique=False
    )
    op.create_table(
        "evidences",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("public_summary", sa.Text(), nullable=True),
        sa.Column(
            "evidence_type",
            sa.Enum(
                "DOCUMENT",
                "SCREENSHOT",
                "API_CHECK",
                "POLICY",
                "CERTIFICATE",
                "MANUAL_ATTESTATION",
                "LINK",
                name="evidencetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "confidentiality",
            sa.Enum(
                "PUBLIC",
                "SHARED_SUMMARY",
                "CONFIDENTIAL",
                "RESTRICTED",
                name="confidentiality",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=500), nullable=True),
        sa.Column("object_key", sa.String(length=600), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidences_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_evidences_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidences")),
        sa.UniqueConstraint("object_key", name=op.f("uq_evidences_object_key")),
    )
    op.create_index(op.f("ix_evidences_deleted_at"), "evidences", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_evidences_expires_at"), "evidences", ["expires_at"], unique=False)
    op.create_index(
        "ix_evidences_org_expiration", "evidences", ["organization_id", "expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_evidences_organization_id"), "evidences", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_evidences_sha256"), "evidences", ["sha256"], unique=False)
    op.create_table(
        "frameworks",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_frameworks_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_frameworks")),
    )
    op.create_index(op.f("ix_frameworks_is_global"), "frameworks", ["is_global"], unique=False)
    op.create_index(op.f("ix_frameworks_name"), "frameworks", ["name"], unique=False)
    op.create_index(
        op.f("ix_frameworks_organization_id"), "frameworks", ["organization_id"], unique=False
    )
    op.create_table(
        "invitations",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "ANALYST", "VIEWER", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invited_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint(
            "organization_id", "email", name=op.f("uq_invitations_organization_id")
        ),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        op.f("ix_invitations_organization_id"), "invitations", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "ANALYST", "VIEWER", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "questionnaires",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("source_format", sa.String(length=10), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "IMPORTED",
                "PROCESSING",
                "READY",
                "IN_REVIEW",
                "COMPLETED",
                "EXPORTED",
                "FAILED",
                name="questionnairestate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("question_column", sa.String(length=255), nullable=False),
        sa.Column("original_columns", sa.JSON(), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.Column("imported_by_id", sa.Uuid(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["imported_by_id"],
            ["users.id"],
            name=op.f("fk_questionnaires_imported_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_questionnaires_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaires")),
    )
    op.create_index(
        op.f("ix_questionnaires_deleted_at"), "questionnaires", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_questionnaires_organization_id"),
        "questionnaires",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_questionnaires_state"), "questionnaires", ["state"], unique=False)
    op.create_table(
        "share_links",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_share_links_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_share_links_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_links")),
    )
    op.create_index(op.f("ix_share_links_expires_at"), "share_links", ["expires_at"], unique=False)
    op.create_index(
        op.f("ix_share_links_organization_id"), "share_links", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_share_links_revoked_at"), "share_links", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_share_links_token_hash"), "share_links", ["token_hash"], unique=True)
    op.create_table(
        "ai_usage_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("questionnaire_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_usage_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_id"],
            ["questionnaires.id"],
            name=op.f("fk_ai_usage_events_questionnaire_id_questionnaires"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_usage_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage_events")),
    )
    op.create_index(
        op.f("ix_ai_usage_events_organization_id"),
        "ai_usage_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_events_questionnaire_id"),
        "ai_usage_events",
        ["questionnaire_id"],
        unique=False,
    )
    op.create_table(
        "controls",
        sa.Column("framework_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=120), nullable=False),
        sa.Column("guidance", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_id"],
            ["frameworks.id"],
            name=op.f("fk_controls_framework_id_frameworks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_controls")),
        sa.UniqueConstraint("framework_id", "code", name=op.f("uq_controls_framework_id")),
    )
    op.create_index(op.f("ix_controls_category"), "controls", ["category"], unique=False)
    op.create_index(op.f("ix_controls_framework_id"), "controls", ["framework_id"], unique=False)
    op.create_table(
        "evidence_versions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=600), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("mime_type", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_evidence_versions_created_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
            name=op.f("fk_evidence_versions_evidence_id_evidences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_versions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_versions")),
        sa.UniqueConstraint(
            "evidence_id", "version_number", name=op.f("uq_evidence_versions_evidence_id")
        ),
    )
    op.create_index(
        op.f("ix_evidence_versions_evidence_id"), "evidence_versions", ["evidence_id"], unique=False
    )
    op.create_index(
        op.f("ix_evidence_versions_organization_id"),
        "evidence_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "questionnaire_questions",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("questionnaire_id", sa.Uuid(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("original_row", sa.JSON(), nullable=False),
        sa.Column(
            "answer_status",
            sa.Enum(
                "UNANSWERED",
                "GENERATED",
                "NEEDS_INFORMATION",
                "APPROVED",
                "REJECTED",
                "MANUALLY_ANSWERED",
                name="answerstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_questionnaire_questions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_id"],
            ["questionnaires.id"],
            name=op.f("fk_questionnaire_questions_questionnaire_id_questionnaires"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questionnaire_questions")),
        sa.UniqueConstraint(
            "questionnaire_id",
            "display_order",
            name=op.f("uq_questionnaire_questions_questionnaire_id"),
        ),
    )
    op.create_index(
        op.f("ix_questionnaire_questions_answer_status"),
        "questionnaire_questions",
        ["answer_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questionnaire_questions_organization_id"),
        "questionnaire_questions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questionnaire_questions_questionnaire_id"),
        "questionnaire_questions",
        ["questionnaire_id"],
        unique=False,
    )
    op.create_table(
        "share_link_evidences",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("share_link_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
            name=op.f("fk_share_link_evidences_evidence_id_evidences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_share_link_evidences_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["share_link_id"],
            ["share_links.id"],
            name=op.f("fk_share_link_evidences_share_link_id_share_links"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_link_evidences")),
        sa.UniqueConstraint(
            "share_link_id", "evidence_id", name=op.f("uq_share_link_evidences_share_link_id")
        ),
    )
    op.create_index(
        op.f("ix_share_link_evidences_organization_id"),
        "share_link_evidences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_share_link_evidences_share_link_id"),
        "share_link_evidences",
        ["share_link_id"],
        unique=False,
    )
    op.create_table(
        "control_mappings",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("source_control_id", sa.Uuid(), nullable=False),
        sa.Column("target_control_id", sa.Uuid(), nullable=False),
        sa.Column("mapping_type", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_control_mappings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_control_id"],
            ["controls.id"],
            name=op.f("fk_control_mappings_source_control_id_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_control_id"],
            ["controls.id"],
            name=op.f("fk_control_mappings_target_control_id_controls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_control_mappings")),
        sa.UniqueConstraint(
            "source_control_id",
            "target_control_id",
            name=op.f("uq_control_mappings_source_control_id"),
        ),
    )
    op.create_index(
        op.f("ix_control_mappings_organization_id"),
        "control_mappings",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_mappings_source_control_id"),
        "control_mappings",
        ["source_control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_control_mappings_target_control_id"),
        "control_mappings",
        ["target_control_id"],
        unique=False,
    )
    op.create_table(
        "evidence_control_links",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
            name=op.f("fk_evidence_control_links_control_id_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
            name=op.f("fk_evidence_control_links_evidence_id_evidences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_control_links_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_control_links")),
        sa.UniqueConstraint(
            "organization_id",
            "evidence_id",
            "control_id",
            name=op.f("uq_evidence_control_links_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_evidence_control_links_control_id"),
        "evidence_control_links",
        ["control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_control_links_evidence_id"),
        "evidence_control_links",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evidence_control_links_organization_id"),
        "evidence_control_links",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "organization_controls",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_ASSESSED",
                "NOT_IMPLEMENTED",
                "PARTIAL",
                "IMPLEMENTED",
                "VERIFIED",
                "NOT_APPLICABLE",
                name="controlstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
            name=op.f("fk_organization_controls_control_id_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_organization_controls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_organization_controls_updated_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_controls")),
        sa.UniqueConstraint(
            "organization_id", "control_id", name=op.f("uq_organization_controls_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_organization_controls_organization_id"),
        "organization_controls",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_controls_status"), "organization_controls", ["status"], unique=False
    )
    op.create_table(
        "share_link_controls",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("share_link_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["controls.id"],
            name=op.f("fk_share_link_controls_control_id_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_share_link_controls_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["share_link_id"],
            ["share_links.id"],
            name=op.f("fk_share_link_controls_share_link_id_share_links"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_link_controls")),
        sa.UniqueConstraint(
            "share_link_id", "control_id", name=op.f("uq_share_link_controls_share_link_id")
        ),
    )
    op.create_index(
        op.f("ix_share_link_controls_organization_id"),
        "share_link_controls",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_share_link_controls_share_link_id"),
        "share_link_controls",
        ["share_link_id"],
        unique=False,
    )
    op.create_table(
        "suggested_answers",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("proposed_answer", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("missing_information", sa.JSON(), nullable=False),
        sa.Column("risk_flags", sa.JSON(), nullable=False),
        sa.Column("control_ids", sa.JSON(), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=160), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_answer", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
            name=op.f("fk_suggested_answers_approved_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_suggested_answers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questionnaire_questions.id"],
            name=op.f("fk_suggested_answers_question_id_questionnaire_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggested_answers")),
    )
    op.create_index(
        "ix_answers_org_question",
        "suggested_answers",
        ["organization_id", "question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_suggested_answers_organization_id"),
        "suggested_answers",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_suggested_answers_question_id"), "suggested_answers", ["question_id"], unique=False
    )
    op.create_table(
        "answer_evidence_links",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["suggested_answers.id"],
            name=op.f("fk_answer_evidence_links_answer_id_suggested_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidences.id"],
            name=op.f("fk_answer_evidence_links_evidence_id_evidences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_answer_evidence_links_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answer_evidence_links")),
        sa.UniqueConstraint(
            "organization_id",
            "answer_id",
            "evidence_id",
            name=op.f("uq_answer_evidence_links_organization_id"),
        ),
    )
    op.create_index(
        op.f("ix_answer_evidence_links_answer_id"),
        "answer_evidence_links",
        ["answer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_answer_evidence_links_evidence_id"),
        "answer_evidence_links",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_answer_evidence_links_organization_id"),
        "answer_evidence_links",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_answer_evidence_links_organization_id"), table_name="answer_evidence_links"
    )
    op.drop_index(op.f("ix_answer_evidence_links_evidence_id"), table_name="answer_evidence_links")
    op.drop_index(op.f("ix_answer_evidence_links_answer_id"), table_name="answer_evidence_links")
    op.drop_table("answer_evidence_links")
    op.drop_index(op.f("ix_suggested_answers_question_id"), table_name="suggested_answers")
    op.drop_index(op.f("ix_suggested_answers_organization_id"), table_name="suggested_answers")
    op.drop_index("ix_answers_org_question", table_name="suggested_answers")
    op.drop_table("suggested_answers")
    op.drop_index(op.f("ix_share_link_controls_share_link_id"), table_name="share_link_controls")
    op.drop_index(op.f("ix_share_link_controls_organization_id"), table_name="share_link_controls")
    op.drop_table("share_link_controls")
    op.drop_index(op.f("ix_organization_controls_status"), table_name="organization_controls")
    op.drop_index(
        op.f("ix_organization_controls_organization_id"), table_name="organization_controls"
    )
    op.drop_table("organization_controls")
    op.drop_index(
        op.f("ix_evidence_control_links_organization_id"), table_name="evidence_control_links"
    )
    op.drop_index(
        op.f("ix_evidence_control_links_evidence_id"), table_name="evidence_control_links"
    )
    op.drop_index(op.f("ix_evidence_control_links_control_id"), table_name="evidence_control_links")
    op.drop_table("evidence_control_links")
    op.drop_index(op.f("ix_control_mappings_target_control_id"), table_name="control_mappings")
    op.drop_index(op.f("ix_control_mappings_source_control_id"), table_name="control_mappings")
    op.drop_index(op.f("ix_control_mappings_organization_id"), table_name="control_mappings")
    op.drop_table("control_mappings")
    op.drop_index(op.f("ix_share_link_evidences_share_link_id"), table_name="share_link_evidences")
    op.drop_index(
        op.f("ix_share_link_evidences_organization_id"), table_name="share_link_evidences"
    )
    op.drop_table("share_link_evidences")
    op.drop_index(
        op.f("ix_questionnaire_questions_questionnaire_id"), table_name="questionnaire_questions"
    )
    op.drop_index(
        op.f("ix_questionnaire_questions_organization_id"), table_name="questionnaire_questions"
    )
    op.drop_index(
        op.f("ix_questionnaire_questions_answer_status"), table_name="questionnaire_questions"
    )
    op.drop_table("questionnaire_questions")
    op.drop_index(op.f("ix_evidence_versions_organization_id"), table_name="evidence_versions")
    op.drop_index(op.f("ix_evidence_versions_evidence_id"), table_name="evidence_versions")
    op.drop_table("evidence_versions")
    op.drop_index(op.f("ix_controls_framework_id"), table_name="controls")
    op.drop_index(op.f("ix_controls_category"), table_name="controls")
    op.drop_table("controls")
    op.drop_index(op.f("ix_ai_usage_events_questionnaire_id"), table_name="ai_usage_events")
    op.drop_index(op.f("ix_ai_usage_events_organization_id"), table_name="ai_usage_events")
    op.drop_table("ai_usage_events")
    op.drop_index(op.f("ix_share_links_token_hash"), table_name="share_links")
    op.drop_index(op.f("ix_share_links_revoked_at"), table_name="share_links")
    op.drop_index(op.f("ix_share_links_organization_id"), table_name="share_links")
    op.drop_index(op.f("ix_share_links_expires_at"), table_name="share_links")
    op.drop_table("share_links")
    op.drop_index(op.f("ix_questionnaires_state"), table_name="questionnaires")
    op.drop_index(op.f("ix_questionnaires_organization_id"), table_name="questionnaires")
    op.drop_index(op.f("ix_questionnaires_deleted_at"), table_name="questionnaires")
    op.drop_table("questionnaires")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_invitations_organization_id"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index(op.f("ix_frameworks_organization_id"), table_name="frameworks")
    op.drop_index(op.f("ix_frameworks_name"), table_name="frameworks")
    op.drop_index(op.f("ix_frameworks_is_global"), table_name="frameworks")
    op.drop_table("frameworks")
    op.drop_index(op.f("ix_evidences_sha256"), table_name="evidences")
    op.drop_index(op.f("ix_evidences_organization_id"), table_name="evidences")
    op.drop_index("ix_evidences_org_expiration", table_name="evidences")
    op.drop_index(op.f("ix_evidences_expires_at"), table_name="evidences")
    op.drop_index(op.f("ix_evidences_deleted_at"), table_name="evidences")
    op.drop_table("evidences")
    op.drop_index("ix_audit_org_created", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")
    op.drop_index(op.f("ix_organizations_deleted_at"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
